#!/bin/bash


#absolute path to this script
cd /home/andrey/Geometry/Geometry\ Book/

#update output files
mdbook build 

#implement preferences
cd config_files
./add_icons.py
./wrap_sections.py
#./import_styles.py
./import_scripts.py

cp -R css/icons ../book/config_files/css

case $1 in 
	-o | --open)
        
		cd ../book
        firefox index.html #run index.html to view changes
        ;;
esac
